USE [master]
GO
/****** Object:  Database [GLS]    Script Date: 04/11/2017 3:36:41 PM ******/
CREATE DATABASE [GLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\GLSDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\GLSDB_1.ldf' , SIZE = 24384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [GLS] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [GLS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GLS] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [GLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GLS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GLS] SET RECOVERY FULL 
GO
ALTER DATABASE [GLS] SET  MULTI_USER 
GO
ALTER DATABASE [GLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'GLS', N'ON'
GO
USE [GLS]
GO
USE [GLS]
GO
/****** Object:  Sequence [dbo].[CountBy]    Script Date: 04/11/2017 3:36:42 PM ******/
CREATE SEQUENCE [dbo].[CountBy] 
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO
USE [GLS]
GO
/****** Object:  Sequence [dbo].[GLS_SEQ]    Script Date: 04/11/2017 3:36:42 PM ******/
CREATE SEQUENCE [dbo].[GLS_SEQ] 
 AS [bigint]
 START WITH 1203003
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO
/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CATEGORIES](
	[CATEGORYID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[BOCREATEDBY] [varchar](30) NOT NULL,
	[BODATECREATED] [date] NULL,
	[BODATEMODIFIED] [date] NULL,
	[BOMODIFIEDBY] [varchar](255) NOT NULL,
	[CATEGORYCODE] [varchar](50) NOT NULL,
	[CATEGORYTYPE] [varchar](30) NOT NULL,
	[CATEGORYVALUE] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CATEGORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[COUNTRY_CODES]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COUNTRY_CODES](
	[COUNTRY_CODE] [varchar](5) NOT NULL,
	[COUNTRY_ID] [int] NULL,
	[COUNTRY_NAME] [varchar](50) NOT NULL,
	[ENABLED_FLG] [varchar](1) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COUNTRY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CURRENCY_CODES]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CURRENCY_CODES](
	[CURRENCY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CURERNCY_NAME] [varchar](50) NOT NULL,
	[CURRENCY_CODE] [varchar](3) NOT NULL,
	[ENABLED_FLG] [varchar](1) NOT NULL,
	[RCRE_TIME] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CURRENCY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DAILY_TRANSACTIONS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DAILY_TRANSACTIONS_TABLE](
	[TRAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORACID] [varchar](30) NULL,
	[BANK_TRAN_ID] [varchar](255) NULL,
	[DEL_FLG] [varchar](30) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[PSTD_FLG] [varchar](30) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[SUB_GROUP_CODE] [varchar](255) NULL,
	[TRAN_AMT] [numeric](20, 2) NULL,
	[TRAN_DATE] [date] NULL,
	[TRAN_PARTICULARS] [varchar](60) NULL,
	[TRAN_TYPE] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[TRAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[FINACLE_USERS]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FINACLE_USERS](
	[USER_NAME] [varchar](30) NULL,
	[SOL_ID] [varchar](4) NULL,
	[ROLE_DESC] [varchar](4) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GENERAL_ACCT_MAST_AUDIT_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENERAL_ACCT_MAST_AUDIT_TABLE](
	[SNO] [int] IDENTITY(1,1) NOT NULL,
	[ACCT_CRNCY_CODE] [varchar](3) NULL,
	[ACCT_MGR_USER_ID] [varchar](15) NULL,
	[ACCT_NAME] [varchar](80) NULL,
	[ACCT_OPN_DATE] [date] NULL,
	[ACCT_OWNERSHIP] [varchar](1) NULL,
	[CREDIT_RATING] [varchar](2) NULL,
	[ACID] [varchar](20) NULL,
	[BANK_ID] [varchar](8) NULL,
	[CLR_BAL_AMT] [float] NULL,
	[CUST_ID] [numeric](10, 0) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[DRWNG_POWER] [float] NULL,
	[ENTITY_CRE_FLG] [varchar](1) NULL,
	[FORACID] [varchar](16) NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](15) NULL,
	[LIEN_AMT] [float] NULL,
	[MAPPED_FLG] [varchar](2) NULL,
	[MEMBER_STATUS] [varchar](2) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](15) NULL,
	[SANCT_LIM] [float] NULL,
	[SCHM_CODE] [varchar](5) NULL,
	[SCHM_TYPE] [varchar](3) NULL,
	[SOL_ID] [int] NULL,
	[SUB_GROUP_CODE] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GENERAL_ACCT_MAST_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENERAL_ACCT_MAST_TABLE](
	[ACID] [varchar](11) NOT NULL,
	[ACCT_CRNCY_CODE] [varchar](3) NOT NULL,
	[ACCT_MGR_USER_ID] [varchar](15) NULL,
	[ACCT_NAME] [varchar](80) NOT NULL,
	[ACCT_OPN_DATE] [date] NULL,
	[ACCT_OWNERSHIP] [varchar](1) NOT NULL,
	[CREDIT_RATING] [varchar](2) NULL,
	[BANK_ID] [varchar](8) NULL,
	[CLR_BAL_AMT] [float] NOT NULL,
	[CUST_ID] [numeric](10, 0) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[DRWNG_POWER] [float] NOT NULL,
	[ENTITY_CRE_FLG] [varchar](1) NOT NULL,
	[FORACID] [varchar](16) NOT NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](15) NOT NULL,
	[LIEN_AMT] [float] NOT NULL,
	[MAPPED_FLG] [varchar](2) NULL,
	[MEMBER_STATUS] [varchar](2) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](15) NOT NULL,
	[REG_DATE] [date] NULL,
	[SANCT_LIM] [float] NOT NULL,
	[SCHM_CODE] [varchar](5) NOT NULL,
	[SCHM_TYPE] [varchar](3) NOT NULL,
	[SOL_ID] [int] NULL,
	[SUB_GROUP_CODE] [varchar](10) NULL,
	[acct_type] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GENERAL_ACCT_MAST_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENERAL_ACCT_MAST_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCT_CRNCY_CODE] [varchar](3) NULL,
	[ACCT_MGR_USER_ID] [varchar](15) NULL,
	[ACCT_NAME] [varchar](80) NULL,
	[ACCT_OPN_DATE] [date] NULL,
	[ACCT_OWNERSHIP] [varchar](1) NULL,
	[CREDIT_RATING] [varchar](2) NULL,
	[ACID] [varchar](20) NULL,
	[BANK_ID] [varchar](8) NULL,
	[CLR_BAL_AMT] [float] NULL,
	[CUST_ID] [numeric](10, 0) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[DRWNG_POWER] [float] NULL,
	[ENTITY_CRE_FLG] [varchar](1) NULL,
	[FORACID] [varchar](16) NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[LAST_OPER] [varchar](1) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](15) NULL,
	[LIEN_AMT] [float] NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](15) NULL,
	[SANCT_LIM] [float] NULL,
	[SCHM_CODE] [varchar](5) NULL,
	[SCHM_TYPE] [varchar](3) NULL,
	[SOL_ID] [int] NULL,
	[SUB_GROUP_CODE] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GROUPS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GROUPS_TABLE](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[BRANCH_NAME] [varchar](50) NOT NULL,
	[COUNTRY_CODE] [varchar](2) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[FIRST_MEET_DATE] [date] NULL,
	[FORMATION_DATE] [date] NULL,
	[GP_CHAIR] [varchar](50) NULL,
	[GP_REGION] [varchar](50) NOT NULL,
	[GP_SECRETARY] [varchar](50) NULL,
	[GP_STATUS] [varchar](20) NOT NULL,
	[GP_STATUS_CODE] [varchar](20) NOT NULL,
	[GP_TREASURER] [varchar](50) NULL,
	[GROUP_ADDRESS] [varchar](50) NOT NULL,
	[GROUP_CENTER] [varchar](50) NOT NULL,
	[GROUP_CODE] [varchar](10) NOT NULL,
	[GROUP_LOANS] [float] NOT NULL,
	[GROUP_NAME] [varchar](50) NOT NULL,
	[GROUP_PHONE] [varchar](20) NOT NULL,
	[GROUP_TYPE] [varchar](2) NOT NULL,
	[GROUP_VILLAGE] [varchar](50) NOT NULL,
	[GRP_MGR_ID] [varchar](30) NOT NULL,
	[GRP_REG_NO] [varchar](30) NOT NULL,
	[LCHG_DATE] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[LOAN_ACCOUNTS] [numeric](10, 0) NOT NULL,
	[MAX_ALLOWED_MEMBERS] [numeric](10, 0) NOT NULL,
	[MAX_ALLOWED_SUB_GRPS] [numeric](10, 0) NOT NULL,
	[MEET_FREQUENCY] [varchar](10) NOT NULL,
	[MEET_PLACE] [varchar](50) NOT NULL,
	[MEET_TIME] [varchar](20) NULL,
	[NO_OF_MEMBERS] [numeric](10, 0) NOT NULL,
	[NO_OF_SUB_GRPS] [numeric](10, 0) NOT NULL,
	[NXT_MEET_DATE] [date] NULL,
	[OUTSTANDING_BAL] [float] NOT NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[SAVING_ACCOUNTS] [numeric](10, 0) NOT NULL,
	[SAVINGS_AMT] [float] NOT NULL,
	[SOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GROUPS_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GROUPS_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[BRANCH_NAME] [varchar](50) NULL,
	[COUNTRY_CODE] [varchar](2) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[FIRST_MEET_DATE] [date] NULL,
	[FORMATION_DATE] [date] NULL,
	[GP_CHAIR] [varchar](50) NULL,
	[GP_REGION] [varchar](50) NULL,
	[GP_SECRETARY] [varchar](50) NULL,
	[GP_STATUS] [varchar](20) NULL,
	[GP_STATUS_CODE] [varchar](20) NULL,
	[GP_TREASURER] [varchar](50) NULL,
	[GROUP_ADDRESS] [varchar](50) NULL,
	[GROUP_CENTER] [varchar](50) NULL,
	[GROUP_CODE] [varchar](10) NULL,
	[GROUP_ID] [int] NULL,
	[GROUP_LOANS] [float] NULL,
	[GROUP_NAME] [varchar](50) NULL,
	[GROUP_PHONE] [varchar](20) NULL,
	[GROUP_VILLAGE] [varchar](50) NULL,
	[GRP_MGR_ID] [varchar](30) NULL,
	[GRP_REG_NO] [varchar](30) NULL,
	[LAST_OPER] [varchar](1) NULL,
	[LCHG_DATE] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[LOAN_ACCOUNTS] [numeric](10, 0) NULL,
	[MAX_ALLOWED_MEMBERS] [numeric](10, 0) NULL,
	[MAX_ALLOWED_SUB_GRPS] [numeric](10, 0) NULL,
	[MEET_FREQUENCY] [varchar](10) NULL,
	[MEET_PLACE] [varchar](50) NULL,
	[MEET_TIME] [varchar](20) NULL,
	[NO_OF_MEMBERS] [numeric](10, 0) NULL,
	[NO_OF_SUB_GRPS] [numeric](10, 0) NULL,
	[NXT_MEET_DATE] [date] NULL,
	[OUTSTANDING_BAL] [float] NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[SAVING_ACCOUNTS] [numeric](10, 0) NULL,
	[SAVINGS_AMT] [float] NULL,
	[SOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[HISTORY_TRANSACTIONS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HISTORY_TRANSACTIONS_TABLE](
	[TRAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORACID] [varchar](20) NULL,
	[BANK_TRAN_ID] [varchar](255) NULL,
	[DEL_FLG] [varchar](2) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](20) NULL,
	[PSTD_FLG] [varchar](2) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](20) NULL,
	[SUB_GROUP_CODE] [varchar](255) NULL,
	[TRAN_AMT] [numeric](20, 4) NULL,
	[TRAN_DATE] [date] NULL,
	[TRAN_PARTICULARS] [varchar](60) NULL,
	[TRAN_TYPE] [varchar](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[TRAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LA_AMORT_SHDL_TABLE_REPORT]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LA_AMORT_SHDL_TABLE_REPORT](
	[ACID] [varchar](11) NOT NULL,
	[ADJ_INT] [float] NOT NULL,
	[ADJ_PRINC] [float] NOT NULL,
	[AMORT_ID] [numeric](19, 0) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[EXPC_BAL] [float] NOT NULL,
	[FLOW_DATE] [date] NOT NULL,
	[INT_DMD] [float] NOT NULL,
	[PAYMENT_INDEX] [numeric](19, 0) NOT NULL,
	[PRINC_DMD] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LA_DMD_TABLE_REPORT]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LA_DMD_TABLE_REPORT](
	[ACID] [varchar](11) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[DMD_AMT] [numeric](20, 0) NOT NULL,
	[DMD_DATE] [date] NOT NULL,
	[DMD_EFF_DATE] [date] NOT NULL,
	[DMD_FLOW_ID] [varchar](5) NOT NULL,
	[DMD_ID] [numeric](19, 0) NOT NULL,
	[DMD_OVDU_DATE] [date] NOT NULL,
	[LAST_ADJ_DATE] [date] NOT NULL,
	[LCHG_TIME] [date] NOT NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[LD_FREQ_TYPE] [varchar](1) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[TOT_ADJ_AMT] [numeric](20, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LA_REP_SHDL_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LA_REP_SHDL_TABLE](
	[ACID] [varchar](11) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[ENTITY_CRE_FLG] [varchar](1) NULL,
	[FLOW_AMT] [numeric](20, 0) NULL,
	[FLOW_START_DATE] [date] NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[NEXT_DMD_DATE] [date] NULL,
	[NUM_OF_FLOWS] [numeric](19, 0) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[SHDL_ID] [numeric](19, 0) NULL,
	[SOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LA_TRAN_DETAIL_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LA_TRAN_DETAIL_TABLE](
	[TRAN_ID] [numeric](19, 0) NOT NULL,
	[ACCOUNT_NO] [numeric](19, 0) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[LCHG_TIME] [date] NOT NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[SUB_TRAN_TYPE] [varchar](2) NOT NULL,
	[TRAN_AMT] [numeric](22, 0) NOT NULL,
	[TRAN_DATE] [date] NOT NULL,
	[VALUE_DATE] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAN_DEMANDS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAN_DEMANDS_TABLE](
	[ACID] [varchar](11) NOT NULL,
	[DMD_AMT] [numeric](20, 4) NULL,
	[DMD_DATE] [date] NULL,
	[STATUS] [varchar](2) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAN_DETAILS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAN_DETAILS_TABLE](
	[ACID] [varchar](11) NOT NULL,
	[DIS_AMT] [float] NULL,
	[DIS_SHDL_DATE] [date] NULL,
	[NUM_ADVANCE_INSTLMNT] [numeric](19, 0) NULL,
	[REPHASEMENT_PRINCIPAL] [float] NULL,
	[UPFRONT_INSTL_AMT] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOGGED_IN_USER]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOGGED_IN_USER](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOGGED_IN_TIME] [date] NOT NULL,
	[SESSION_ID] [varchar](200) NULL,
	[SOL_ID] [int] NULL,
	[USER_NAME] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[REGIONS_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGIONS_TABLE](
	[REGION_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[COUNTRY_CODE] [varchar](2) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[REGION_NAME] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REGION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[REGIONS_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGIONS_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[COUNTRY_CODE] [varchar](2) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[REGION_ID] [int] NULL,
	[REGION_NAME] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RES_MAPPING]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RES_MAPPING](
	[MAP_ID] [int] IDENTITY(1,1) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[MOP_ID] [varchar](10) NOT NULL,
	[MOP_TEXT] [varchar](60) NOT NULL,
	[MOP_URL] [varchar](100) NOT NULL,
	[RCRE_REP] [varchar](20) NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER] [varchar](30) NOT NULL,
	[RES_ID] [int] NOT NULL,
	[ROLE_NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RES_MAPPING_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RES_MAPPING_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[DEL_FLG] [varchar](1) NULL,
	[MAP_ID] [int] NULL,
	[MOP_ID] [varchar](10) NULL,
	[MOP_TEXT] [varchar](60) NULL,
	[MOP_URL] [varchar](100) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER] [varchar](30) NULL,
	[RES_ID] [int] NULL,
	[ROLE_NAME] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RESOURCES]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RESOURCES](
	[RES_ID] [int] IDENTITY(1,1) NOT NULL,
	[MOP_ID] [varchar](10) NOT NULL,
	[MOP_TEXT] [varchar](60) NOT NULL,
	[MOP_URL] [varchar](100) NOT NULL,
	[RCRE_REP] [varchar](20) NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE_CRNCY_LIMIT_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE_CRNCY_LIMIT_TABLE](
	[LIMIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[CRNCY_CODE] [varchar](3) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[LCHG_DATE] [date] NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[ROLE_ID] [int] NULL,
	[USER_CASH_DR_LIM] [float] NOT NULL,
	[USER_INTERSOL_CASH_DR_LIMIT] [float] NOT NULL,
	[USER_INTERSOL_XFER_DR_LIMIT] [float] NOT NULL,
	[USER_XFER_DR_LIM] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LIMIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE_CRNCY_LIMIT_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE_CRNCY_LIMIT_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[CRNCY_CODE] [varchar](3) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[LCHG_DATE] [date] NULL,
	[LIMIT_ID] [int] NULL,
	[RCRE_TIME] [date] NULL,
	[ROLE_ID] [int] NULL,
	[USER_CASH_DR_LIM] [float] NULL,
	[USER_INTERSOL_CASH_DR_LIMIT] [float] NULL,
	[USER_INTERSOL_XFER_DR_LIMIT] [float] NULL,
	[USER_XFER_DR_LIM] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE_PROFILE_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE_PROFILE_TABLE](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[ENTITY_CRE_FLG] [varchar](1) NOT NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[ROLE_DESC] [varchar](30) NOT NULL,
	[ROLE_DESCRIPTION] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLE_PROFILE_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLE_PROFILE_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[ENTITY_CRE_FLG] [varchar](1) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[ROLE_DESC] [varchar](30) NULL,
	[ROLE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SERVICE_OUTLET_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SERVICE_OUTLET_TABLE](
	[SOL_ID] [int] IDENTITY(1,1) NOT NULL,
	[ADDR_1] [varchar](45) NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[CNTRY_CODE] [varchar](5) NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[HOME_CRNCY_CODE] [varchar](3) NOT NULL,
	[LCHG_TIME] [date] NOT NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[SOL_BOD_DATE] [date] NULL,
	[SOL_CLS_DATE] [date] NULL,
	[SOL_CLS_FLG] [varchar](1) NULL,
	[SOL_DESC] [varchar](132) NULL,
	[SOL_EOD_STATUS] [varchar](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SERVICE_OUTLET_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SERVICE_OUTLET_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[ADDR_1] [varchar](45) NULL,
	[BANK_ID] [varchar](8) NULL,
	[CNTRY_CODE] [varchar](5) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[HOME_CRNCY_CODE] [varchar](3) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[REGION_CODE] [varchar](30) NULL,
	[SOL_BOD_DATE] [date] NULL,
	[SOL_CLS_DATE] [date] NULL,
	[SOL_CLS_FLG] [varchar](1) NULL,
	[SOL_DESC] [varchar](132) NULL,
	[SOL_EOD_STATUS] [varchar](1) NULL,
	[SOL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SOL_GROUP_CONTROL_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SOL_GROUP_CONTROL_TABLE](
	[SOL_GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[DB_STAT_DATE] [date] NOT NULL,
	[DC_CLS_DATE] [date] NOT NULL,
	[DC_CLS_FLG] [varchar](1) NOT NULL,
	[DEF_NUM_OF_DAYS_IN_MTH] [numeric](10, 0) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[GROUP_DESC] [varchar](40) NOT NULL,
	[HOME_CNTRY_CODE] [varchar](5) NOT NULL,
	[HOME_CRNCY_CODE] [varchar](3) NOT NULL,
	[LCHG_TIME] [date] NOT NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[NUM_OF_BACK_DAYS_ALLOWED] [numeric](10, 0) NOT NULL,
	[NUM_OF_FUTURE_DAYS_ALLOWED] [numeric](10, 0) NOT NULL,
	[RCRE_TIME] [date] NOT NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SOL_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SOL_GROUP_CONTROL_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SOL_GROUP_CONTROL_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[DB_STAT_DATE] [date] NULL,
	[DC_CLS_DATE] [date] NULL,
	[DC_CLS_FLG] [varchar](1) NULL,
	[DEF_NUM_OF_DAYS_IN_MTH] [numeric](10, 0) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[GROUP_DESC] [varchar](40) NULL,
	[HOME_CNTRY_CODE] [varchar](5) NULL,
	[HOME_CRNCY_CODE] [varchar](3) NULL,
	[LCHG_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[NUM_OF_BACK_DAYS_ALLOWED] [numeric](10, 0) NULL,
	[NUM_OF_FUTURE_DAYS_ALLOWED] [numeric](10, 0) NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[SOL_GROUP_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUB_GRP_TABLE]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUB_GRP_TABLE](
	[SUB_GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NOT NULL,
	[BRANCH_NAME] [varchar](50) NOT NULL,
	[COUNTRY_CODE] [varchar](2) NOT NULL,
	[DEL_FLG] [varchar](1) NOT NULL,
	[FIRST_MEET_DATE] [date] NULL,
	[FORMATION_DATE] [date] NULL,
	[GROUP_ID] [int] NOT NULL,
	[LCHG_DATE] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NOT NULL,
	[LOAN_ACCOUNTS] [numeric](10, 0) NOT NULL,
	[MAX_ALLOWED_MEMBERS] [numeric](10, 0) NOT NULL,
	[MEET_FREQUENCY] [varchar](10) NOT NULL,
	[MEET_PLACE] [varchar](50) NOT NULL,
	[MEET_TIME] [varchar](20) NULL,
	[NO_OF_MEMBERS] [numeric](10, 0) NOT NULL,
	[NXT_MEET_DATE] [date] NULL,
	[OUTSTANDING_BAL] [float] NOT NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NOT NULL,
	[SAVING_ACCOUNTS] [numeric](10, 0) NOT NULL,
	[SAVINGS_AMT] [float] NOT NULL,
	[SOL_ID] [int] NOT NULL,
	[SUB_GP_CHAIR] [varchar](50) NULL,
	[SUB_GP_REGION] [varchar](50) NOT NULL,
	[SUB_GP_SECRETARY] [varchar](50) NULL,
	[SUB_GP_STATUS] [varchar](20) NOT NULL,
	[SUB_GP_STATUS_CODE] [varchar](20) NOT NULL,
	[SUB_GP_TREASURER] [varchar](50) NULL,
	[SUB_GROUP_ADDRESS] [varchar](50) NOT NULL,
	[SUB_GROUP_CENTER] [varchar](50) NOT NULL,
	[SUB_GROUP_CODE] [varchar](10) NOT NULL,
	[SUB_GROUP_LOANS] [float] NOT NULL,
	[SUB_GROUP_NAME] [varchar](50) NOT NULL,
	[SUB_GROUP_PHONE] [varchar](20) NOT NULL,
	[SUB_GROUP_VILLAGE] [varchar](50) NOT NULL,
	[SUB_GRP_ACNT_NAME] [varchar](80) NOT NULL,
	[SUB_GRP_ACNT_NO] [varchar](20) NOT NULL,
	[SUB_GRP_MGR_ID] [varchar](30) NOT NULL,
	[SUB_GRP_REG_NO] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SUB_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUB_GRP_TABLE_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUB_GRP_TABLE_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[BANK_ID] [varchar](8) NULL,
	[BRANCH_NAME] [varchar](50) NULL,
	[COUNTRY_CODE] [varchar](2) NULL,
	[DEL_FLG] [varchar](1) NULL,
	[FIRST_MEET_DATE] [date] NULL,
	[FORMATION_DATE] [date] NULL,
	[GROUP_ID] [int] NULL,
	[LAST_OPER] [varchar](1) NULL,
	[LCHG_DATE] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[LOAN_ACCOUNTS] [numeric](10, 0) NULL,
	[MAX_ALLOWED_MEMBERS] [numeric](10, 0) NULL,
	[MEET_FREQUENCY] [varchar](10) NULL,
	[MEET_PLACE] [varchar](50) NULL,
	[MEET_TIME] [varchar](20) NULL,
	[NO_OF_MEMBERS] [numeric](10, 0) NULL,
	[NXT_MEET_DATE] [date] NULL,
	[OUTSTANDING_BAL] [float] NULL,
	[RCRE_TIME] [date] NULL,
	[RCRE_USER_ID] [varchar](30) NULL,
	[SAVING_ACCOUNTS] [numeric](10, 0) NULL,
	[SAVINGS_AMT] [float] NULL,
	[SOL_ID] [int] NULL,
	[SUB_GP_CHAIR] [varchar](50) NULL,
	[SUB_GP_REGION] [varchar](50) NULL,
	[SUB_GP_SECRETARY] [varchar](50) NULL,
	[SUB_GP_STATUS] [varchar](20) NULL,
	[SUB_GP_STATUS_CODE] [varchar](20) NULL,
	[SUB_GP_TREASURER] [varchar](50) NULL,
	[SUB_GROUP_ADDRESS] [varchar](50) NULL,
	[SUB_GROUP_CENTER] [varchar](50) NULL,
	[SUB_GROUP_CODE] [varchar](10) NULL,
	[SUB_GROUP_ID] [int] NULL,
	[SUB_GROUP_LOANS] [float] NULL,
	[SUB_GROUP_NAME] [varchar](50) NULL,
	[SUB_GROUP_PHONE] [varchar](20) NULL,
	[SUB_GROUP_VILLAGE] [varchar](50) NULL,
	[SUB_GRP_ACNT_NAME] [varchar](80) NULL,
	[SUB_GRP_ACNT_NO] [varchar](20) NULL,
	[SUB_GRP_MGR_ID] [varchar](30) NULL,
	[SUB_GRP_REG_NO] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Test]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test](
	[id] [int] NOT NULL,
	[Date1] [date] NOT NULL,
	[Date2] [date] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[USER_CREDS_TBL]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_CREDS_TBL](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCT_EXPY_DATE] [date] NULL,
	[ACCT_INACTIVE_DAYS] [numeric](10, 0) NULL,
	[DISABLED_FROM_DATE] [date] NULL,
	[DISABLED_UPTO_DATE] [date] NULL,
	[SOL_ID] [int] NOT NULL,
	[LAST_ACCESS_TIME] [date] NULL,
	[LCHG_USER_ID] [varchar](30) NULL,
	[NEW_USER_FLG] [varchar](1) NULL,
	[NUM_PWD_ATTEMPTS] [numeric](10, 0) NULL,
	[NUM_PWD_HISTORY] [numeric](10, 0) NULL,
	[PW_EXPY_DATE] [date] NULL,
	[PWD_HISTORY] [varchar](3072) NULL,
	[ROLE_ID] [varchar](4) NULL,
	[USER_NAME] [varchar](30) NOT NULL,
	[USER_PW] [varchar](100) NULL,
	[USER_STATUS] [varchar](2) NULL,
	[ROLE_DESC] [varchar](8) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER_CREDS_TBL_MOD]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_CREDS_TBL_MOD](
	[MOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCT_EXPY_DATE] [date] NULL,
	[ACCT_INACTIVE_DAYS] [numeric](10, 0) NULL,
	[DISABLED_FROM_DATE] [date] NULL,
	[DISABLED_UPTO_DATE] [date] NULL,
	[LAST_ACCESS_TIME] [date] NULL,
	[LAST_OPER] [varchar](2) NULL,
	[NEW_USER_FLG] [varchar](1) NULL,
	[NUM_PWD_ATTEMPTS] [numeric](10, 0) NULL,
	[NUM_PWD_HISTORY] [numeric](10, 0) NULL,
	[PW_EXPY_DATE] [date] NULL,
	[PWD_HISTORY] [varchar](3072) NULL,
	[RCRE_USER_ID] [varchar](20) NULL,
	[ROLE_ID] [int] NULL,
	[USER_ID] [int] NULL,
	[USER_NAME] [varchar](30) NULL,
	[USER_PW] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  View [dbo].[LOAN_DEMANDS_REPORT]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[LOAN_DEMANDS_REPORT]
AS select g.foracid, g.acct_name, l.DMD_AMT, l.DMD_DATE,g.sub_group_code  from general_acct_mast_table g, loan_demands_table l
where g.acid = l.acid 
and g.SUB_GROUP_CODE is not null
and g.mapped_flg = 'Y'
and g.MEMBER_STATUS = 'A'
and l.status = 'N'
group by g.foracid, g.acct_name, l.DMD_AMT,l.DMD_DATE,g.sub_group_code

GO
/****** Object:  View [dbo].[LOAN_DISBURSEMENT_REPORT]    Script Date: 04/11/2017 3:36:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[LOAN_DISBURSEMENT_REPORT]
AS select g.foracid, g.acct_name, l.DIS_AMT, l.DIS_SHDL_DATE, l.REPHASEMENT_PRINCIPAL, l.NUM_ADVANCE_INSTLMNT, l.UPFRONT_INSTL_AMT,g.sub_group_code  from general_acct_mast_table g, loan_details_table l where g.acid = l.acid and g.SUB_GROUP_CODE is not null
GO
ALTER TABLE [dbo].[GENERAL_ACCT_MAST_TABLE] ADD  DEFAULT ((1)) FOR [acct_type]
GO
ALTER TABLE [dbo].[ROLE_PROFILE_TABLE] ADD  DEFAULT ('Mgr Card Centre Cr') FOR [ROLE_DESCRIPTION]
GO
ALTER TABLE [dbo].[USER_CREDS_TBL] ADD  DEFAULT ('DBA') FOR [ROLE_DESC]
GO
ALTER TABLE [dbo].[RES_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_ID_RES_MAPPING] FOREIGN KEY([RES_ID])
REFERENCES [dbo].[RESOURCES] ([RES_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RES_MAPPING] CHECK CONSTRAINT [FK_ROLE_ID_RES_MAPPING]
GO
USE [master]
GO
ALTER DATABASE [GLS] SET  READ_WRITE 
GO

